apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-vault-secrets
spec:
  destination:
    name: ''
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: demo/argocd
    repoURL: 'https://github.com/acidonper/ocp-gitops-argocd-with-vault-secrets'
    targetRevision: demo
    plugin:
      name: argocd-vault-plugin
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false  